# Generated by Django 2.2.2 on 2019-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190701_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(upload_to='media/avatar', verbose_name='user_image'),
        ),
    ]
