language: python
python:
  - '3.6'
script:
  - cd dbbus/
  - python manage.py test

services: postgresql

env:
  - DJANGO=2.2.3

before_install:
  - export DJANGO_SETTINGS_MODULE=dbbus.settings
  - export PYTHONPATH=$HOME/builds/mofiebiger/DublinBus
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
notifications:
  slack: dublinbussummerproj.slack.com
