language: python
python:
  - '3.6'
script:
  - python manage.py test
env:
  - DJANGO=2.2.3 DB=postgres
install:
  - pip install -r requirements.txt
notifications:
  slack: dublinbussummerproj.slack.com
