language: python
python:
- '3.6'
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- cd dbbus/
- python manage.py test
services: postgresql
env:
  matrix:
  - DJANGO=2.2.3
  global:
    secure: ShYgO0WWIC+TfNgAAHHMC70MHLk+v6cZjR7k/fNvFh/eAhF+G1rM3qG739J3P7FC37PSM9BuUOdCUMFKIMeknljsFi8W6uUrXHUDC+6EemkPQfDFeswDnHWxeXqrohCW2rOUqi8tNvBxQMyqn8sbi+ZDGnJzorS1nmJV6u20iT3b8R9zbw3KxUMnXM8BQFJhHZBeVvFLxi1c8jCYiBrV0qAvQS55M8CNrlxczlwzOVz1qoKVbRZAfEcyAFKQJcHxjmDtYmHiX9MO48Z3s00kLSUk38hCxqwRWlI89jTnKtwuaPfSvkNUwTHrDZMoyvHkrOwSJ+QouS/CmrHQeFZQVgNz3U37JLfm91EW6kYLgxjbPjmVs2hVCMkTSVGxAA5J4N81KXSZVUS8A4UYjp+BiisPsgcVJwpTfU0NPcvYru4LAxEkPwGLySInjw5LZhlNyTUPoJkQK5Fw8JShAgZfcJiQ84fAnlQCx/2xwFJy1F/Jl1usVpFx+bfgDG4VrMAAFUwc7ihAoyNtW5f51tYCaQnqBwLrVRtPC9ztralXdUou6e0GCG7ZDJR5Puv2HvJYuyYibDaKOvQQPZGhZgCSe7Ef1rFIFhGa4etgvtGJhKNojJogzVOryDvzX/Iihrp4t5RhO3xY52aHOs/MtwQqwLlbQ/H7g5Nzn/TeOKHYJQA=
before_install:
- export DJANGO_SETTINGS_MODULE=dbbus.settings
- export PYTHONPATH=$HOME/builds/mofiebiger/DublinBus
- export PIP_USE_MIRRORS=true
- echo $super_secret_password | gpg --passphrase-fd 0 dbbus/config.py.gpg
install:
- pip install -r requirements.txt
